In [1]:
from sklearn.externals import joblib
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
import numpy as np 
from sklearn import neighbors, cross_validation

C:\Users\Arghyadeep\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [14]:
#tsne_x = joblib.load("xtsne.pkl")
#tsne_y = joblib.load("ytsne.pkl")
pca_new = joblib.load("PCA.pkl")
pca_old = joblib.load("tsnedata.pkl")
pca_label = joblib.load("tsnelabel.pkl")
#tsne_x = tsne_x.values
#tsne_y = tsne_y.values
#tsne = np.concatenate((np.reshape(tsne_x,(1000,1)),np.reshape(tsne_y,(1000,1))), axis = 1)
#print(tsne.shape)
#print(tsne_label.shape)

In [15]:
fit1 = neigh.fit(pca_new,pca_label)
#print(neigh.score(tsne,tsne_label))
#print(neigh.score(tsne_data,tsne_label))

In [16]:
fit2 = neigh.fit(pca_old,pca_label)
#print(neigh.score(tsne_data,tsne_label))

In [17]:
for k in range(1, 10):
    neigh = neighbors.KNeighborsClassifier(n_neighbors=k)
    #neigh.fit(tsne, tsne_label) 
    a = cross_validation.cross_val_score(neigh, pca_new, y=pca_label)
    b = cross_validation.cross_val_score(neigh, pca_old, y=pca_label)
    print(a,"Accuracy for new data[dimension 1000*2] with k = ",k)
    print(b,"Accuracy for old data[dimension 1000*784] with k = ",k)

[ 0.10089021  0.08708709  0.12121212] Accuracy for new data[dimension 1000*2] with k =  1
[ 0.75667656  0.76576577  0.73636364] Accuracy for old data[dimension 1000*784] with k =  1
[ 0.12166172  0.12012012  0.1       ] Accuracy for new data[dimension 1000*2] with k =  2
[ 0.72700297  0.70570571  0.73636364] Accuracy for old data[dimension 1000*784] with k =  2
[ 0.09495549  0.11711712  0.1030303 ] Accuracy for new data[dimension 1000*2] with k =  3
[ 0.72700297  0.73573574  0.72727273] Accuracy for old data[dimension 1000*784] with k =  3
[ 0.09792285  0.1021021   0.0969697 ] Accuracy for new data[dimension 1000*2] with k =  4
[ 0.74480712  0.72972973  0.74848485] Accuracy for old data[dimension 1000*784] with k =  4
[ 0.09198813  0.1021021   0.1       ] Accuracy for new data[dimension 1000*2] with k =  5
[ 0.72997033  0.72372372  0.73030303] Accuracy for old data[dimension 1000*784] with k =  5
[ 0.09495549  0.1021021   0.10606061] Accuracy for new data[dimension 1000*2] with k =  6
